# Ansible pipeline
# Tesing

trigger:
- master
variables:
  SUBSCRIPTION_NAME: Atiku
pool:
  name: "workload"
# #   vmImage: 'ubuntu-latest'

steps:
# - task: UsePythonVersion@0
#   displayName: 'Install Python'
#   inputs:
#     versionSpec: '3.6'

- task: Bash@3
  displayName: 'Install Python, ansible & az ansible module on agent'
  inputs:
    targetType: 'inline'
    script: |
      # Install Python 3 and pip
      sudo apt install -y python3-pip
      
      # Upgrade pip3.
      sudo pip3 install --upgrade pip
      
      #install ansible
      sudo pip3 install ansible
      
      # Install Ansible az collection for interacting with Azure.
      ansible-galaxy collection install azure.azcollection
      
      # Install Ansible modules for Azure
      sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

# - script: pip install ansible
#   displayName: 'Install Ansible'

# - script: pip install -r https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
#   displayName: 'Install Azure modules needed'

# - script: ansible-galaxy collection install azure.azcollection
#   displayName: 'Install Ansible Azure Collection'
- task: Bash@3
  displayName: 'Install Azure Cli'
  inputs:
    targetType: 'inline'
    script: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

- task: AzureCLI@2
  displayName: 'Azure CLI'
  inputs:
    azureSubscription: '$(SUBSCRIPTION_NAME)'
    addSpnToEnvironment: true
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query="id" -o tsv)"
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]${servicePrincipalId}"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]${servicePrincipalKey}"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]${tenantId}"
      ansible localhost -m azure.azcollection.azure_rm_resourcegroup -a "name=ansibleazdevops location=uksouth"
      echo $(ARM_SUBSCRIPTION_ID)
      echo $(ARM_CLIENT_ID)
      echo $(ARM_CLIENT_SECRET)
      echo $(ARM_TENANT_ID)
  
# - script: ansible-playbook -i inv site.yml
#   displayName: 'Run Ansible Playbook'
#   env:
#     AZURE_CLIENT_ID: $(ARM_CLIENT_ID)
#     AZURE_SECRET: $(ARM_CLIENT_SECRET)
#     AZURE_TENANT: $(ARM_TENANT_ID)
#     AZURE_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
